name: chemvae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - numpy=1.19.2
  - pandas=1.1.5
  - pip=21.1.3
  - rdkit=2020.09.1.0
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - tensorflow-gpu=1.15.0
  - keras=2.3.1
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - jupyter
  - pyyaml=5.4.1
  - pip:
    - absl-py==0.15.0