name: vae-emb
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.2
  - numpy=1.19.2
  - pandas=1.3.2
  - pip=21.1.3
  - python=3.7.10
  - rdkit=2020.09.1.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.2
  - setuptools=52.0.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-gpu=1.14.0
  - tqdm=4.61.2