name: vae-emb
channels:
  - pytorch
  - nvidia
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.3.2
  - matplotlib=3.4.2
  - seaborn=0.11.2
  - scikit-learn=1.0.0
  - scipy=1.7.0
  - rdkit=2021.09.4
  - tqdm=4.62.0
  - setuptools=58.0.4
  - pip=21.2.4
  - cudatoolkit=11.2
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - tensorflow-gpu=2.6.0
  - tensorboard=2.6.0
  - pip:
    - torch-geometric