name: chemvae
channels:
  - conda-forge
  - nvidia
dependencies:
  # Core Python and CUDA
  - python=3.9
  - cudatoolkit=11.8
  
  # TensorFlow and Keras
  - tensorflow-gpu=2.14
  - keras-preprocessing
  
  # Scientific computing
  - scikit-learn=1.6
  - numpy
  - pandas
  
  # Visualization
  - matplotlib
  - seaborn
  - pillow
  
  # Chemistry
  - rdkit=2024.09.2
  - deepsmiles=1.0.1
  
  # Utilities
  - jupyter
  - tqdm
  - pyyaml=5.4.1
  - joblib
  
  # CUDA compiler (required for XLA operations)
  - nvidia::cuda-nvcc=12.4.131
  
  # Additional dependencies that may be needed
  - h5py
  - scipy
  - setuptools